### ISSUE TITLE
Implement proving for testnets

### ISSUE THREAD

**Issue by ekrembal** [chainwayxyz/risc0-to-bitvm2#13]
This includes regtest, testnet4, and signet

This circuit should be compilable with a flag, thus, we can select the target system in compile time.

We could make several guest programs for every type but in that case, overall compile time would be huge.

**Comment by ozankaymak** [comment]
How are we going to prove regtest?

**Comment by ozankaymak** [comment]
Also why Signet? We don't even use it. Also, it does not use PoW.
